services:
  postgres:
    image : postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
  back:
    image: gludsito-back:1.0
    container_name: back
    ports:
      - 8080:8080
    networks:
      - backend
volumes:
  data:
networks:
  backend: